name: Supercharger

on:
  push:
    branches:
      - master
      - comingsoon
      - develop
      - uat
jobs:
    Supercharge-App:
      name: Create a new branch
      runs-on: ubuntu-latest
      steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v1
          with:
            php-version: 7.2 # Use your PHP version
            extensions: mbstring, bcmath # Setup any required extensions for tests
        - name: Create a branch
          run: |
              git clone https://github.com/le-yo/supercharger.git
              cd supercharger
              git checkout -b superapp_$(git rev-parse --short "$GITHUB_SHA")
              git push origin superapp_$(git rev-parse --short "$GITHUB_SHA")
