name: Supercharger

on:
  push:
    branches:
      - master
      - comingsoon
      - develop
      - uat
jobs:
    Supercharge-App:
      name: Create a new branch
      runs-on: ubuntu-latest
      steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v1
          with:
            php-version: 7.2 # Use your PHP version
            extensions: mbstring, bcmath # Setup any required extensions for tests
        - name: Create a branch
          run: |
              git clone https://github.com/le-yo/supercharger.git
              cd supercharger
              git config --global user.email "${EMAIL}"
              git config --global user.name "SuperCharger Bot"
              git checkout -b superapp_$(git rev-parse --short "$GITHUB_SHA")
              git remote rm origin
              git remote add origin https://github.com/le-yo/supercharger
              composer create-project --prefer-dist laravel/laravel superapp_$(git rev-parse --short "$GITHUB_SHA")
              git add --all
              git commit -m "New Supercharger App created"
              - run: echo ::set-output name=password::${REPO_TOKEN}
              id: pass
              git push origin superapp_$(git rev-parse --short "$GITHUB_SHA")
              with:
              username: le-yo
              password: ${{ steps.pass.outputs.password }}
