name: Supercharger

on:
  push:
    branches:
      - master
      - comingsoon
      - develop
      - uat
jobs:
    Create-branch:
      name: Create a new branch
      runs-on: ubuntu-latest
      steps:
        - name: New branch
          run: |
              git clone https://github.com/le-yo/supercharger.git
              cd supercharger
              git checkout -b $(git rev-parse --short "$GITHUB_SHA")
